# Generated by Django 3.2.6 on 2021-08-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
