# Generated by Django 3.2.6 on 2021-08-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0002_myuser_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='timezone',
        ),
    ]
