# Generated by Django 3.2.6 on 2021-08-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0003_remove_myuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='myuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=224),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='state',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
